-- 1. Criação da tabela FUNCIONARIO primeiro, pois é referenciada por DEPENDENTE e TRABALHA
-- O campo SUPERVISOR_ID é um autorrelacionamento.
CREATE TABLE FUNCIONARIO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    SUPERVISOR_ID INT,
    FOREIGN KEY (SUPERVISOR_ID) REFERENCES FUNCIONARIO(ID)
);

-- 2. Criação da tabela DEPENDENTE (referencia FUNCIONARIO)
CREATE TABLE DEPENDENTE (
    ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    FUNCIONARIO_ID INT,
    FOREIGN KEY (FUNCIONARIO_ID) 
        REFERENCES FUNCIONARIO(ID) 
        ON DELETE CASCADE
);

-- 3. Criação da tabela PROJETO (não possui chaves estrangeiras, mas é referenciada por TRABALHA)
CREATE TABLE PROJETO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

-- 4. Criação da tabela TRABALHA (referencia FUNCIONARIO e PROJETO)
CREATE TABLE TRABALHA (
    ID INT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    INICIO_PROJETO TIMESTAMP,
    FIM_PROJETO TIMESTAMP,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID),
    FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO(ID)
);

-- 5. Criação da tabela FERRAMENTA (referenciada pela tabela associativa USA_FERRAMENTA)
CREATE TABLE FERRAMENTA (
    ID INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

-- 6. Criação da tabela USA_FERRAMENTA (relacionamento MUITOS PARA MUITOS)
-- Referencia TRABALHA e FERRAMENTA. A chave primária é a combinação de ambas as chaves.
CREATE TABLE USA_FERRAMENTA (
    ID_TRABALHA INT NOT NULL,
    ID_FERRAMENTA INT NOT NULL,
    PRIMARY KEY (ID_TRABALHA, ID_FERRAMENTA),
    FOREIGN KEY (ID_TRABALHA) REFERENCES TRABALHA(ID),
    FOREIGN KEY (ID_FERRAMENTA) REFERENCES FERRAMENTA(ID)
);
